### ISSUE TITLE
I have a bug wit socket 

### ISSUE THREAD

**Issue by DarkCodeStudios** [DJj123dj/open-ticket#99]
![Screenshot_20240718-131646](https://github.com/user-attachments/assets/8cdbefeb-401a-42c4-a8d4-8e55f4c57c93)

**Comment by DarkCodeStudios** [comment]
I'm starting it from stackbliz.com

**Comment by DJj123dj** [comment]
Okay, I recommend first trying & configuring the bot on your local computer before putting it on the hosting. If you still have problems with the hosting, I recommend switching to a paid vps or another hosting.

**Comment by DarkCodeStudios** [comment]
At the moment I don't have money my 32bit pc doesn't support npm :( I'm starting it on slackbliz.com with VSC :(

**Comment by DJj123dj** [comment]
Okay, no problem! But I still recommend searching for another hosting because Open Ticket with all the dependencies is about 60MB and someone in the djdjdev discord found that your hosting only supports 1MB of files for free.
![image](https://github.com/user-attachments/assets/acaf6999-0f15-4ce5-8520-17a138e47d99)

**Comment by DarkCodeStudios** [comment]
Oh , ok :(
